name = "fun-fun-function"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "fun-fun-function_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "fun-fun-function.wasm"
command = "npm run build:release"
